sonar.projectKey=advanced-cicd-razwan
sonar.projectName=Advanced-CICD-Pipeline
sonar.projectVersion=2.0.0
sonar.language=java
sonar.sources=app/src/main
sonar.tests=app/src/test
sonar.java.binaries=app/target/classes
sonar.java.test.binaries=app/target/test-classes
sonar.coverage.exclusions=**/config/**,**/entity/**,**/dto/**
