{
 "title": "Advanced CI/CD App Overview",
 "tags": [
  "advanced-cicd",
  "spring-boot",
  "kubernetes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "JVM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"advanced-cicd\"})"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"advanced-cicd\"}[1m]))"
    }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"advanced-cicd\",pod=~\"advanced-cicd-app-.*\",container!=\"\"}[5m]))"
    }
   ]
  }
 ]
}