apiVersion: v1
kind: Service
metadata:
  name: advanced-cicd-app
  namespace: advanced-cicd
spec:
  type: LoadBalancer
  selector:
    app: advanced-cicd-app
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
