
[jenkins_master]
jenkins-master ansible_host=REPLACE_WITH_JENKINS_MASTER_IP

[jenkins_agent]
jenkins-agent ansible_host=REPLACE_WITH_JENKINS_AGENT_IP

[ansible_controller]
ansible-controller ansible_host=REPLACE_WITH_ANSIBLE_CONTROLLER_IP
